sudo: required
services:
  - docker

before_install:
  - docker build -t harlesbayu/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true harlesbayu/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:  $AWS_SECRET_KEY
  region: "ap-southeast-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_path: "docker-react"
  bucket_name: "elasticbeanstalk-ap-southeast-1-089372333993"
  on:
    branch: master